✨ add wish id in notifications.
patou/liste-envies pull request #110
Opened 2020-10-26 20:54 UTC by manudss

2020-10-27 09:08 UTC, patou requested changes

2020-10-27 09:08 UTC, patou commented on liste-envies-war/src/main/java/fr/desaintsteban/liste/envies/service/WishesService.java
> +                NotificationsService.notify(NotificationType.DELETE_WISH, user, wishList, true, saved.getLabel(), itemid);
Du coup pourquoi ne pas passer directement le wish ?

2020-10-27 09:08 UTC, patou commented on liste-envies-war/src/main/java/fr/desaintsteban/liste/envies/service/AppUserService.java
> +            try {
non, cela n'est pas la solution, il faut dans le `accept` modifier le code en fonction des infos que tu aura dans le user.
Cf issus #111

2020-10-27 14:21 UTC, manudss commented on liste-envies-war/src/main/java/fr/desaintsteban/liste/envies/service/NotificationsService.java
> +		 if (wishId != null) {
Fait quoi ? Le create notifs fait les modifs pour toute les autres fonctions.

2020-10-27 14:24 UTC, manudss commented on liste-envies-war/src/main/java/fr/desaintsteban/liste/envies/service/WishesService.java
> +                NotificationsService.notify(NotificationType.DELETE_WISH, user, wishList, true, saved.getLabel(), itemid);
J'ai commencé à faire cela, mais je me suis rendu compte, qu'on avait pas forcément le wish, juste l'id.

2020-10-27 22:14 UTC, manudss commented on liste-envies-war/src/main/java/fr/desaintsteban/liste/envies/service/NotificationsService.java
> +		 if (wishId != null) {
J'ai fait une mise à jour, pour ne pas avoir de répétitions.

2020-10-28 09:20 UTC, patou commented on liste-envies-war/src/main/java/fr/desaintsteban/liste/envies/service/WishesService.java
> +                    NotificationsService.notify(NotificationType.ADD_NOTE, user, wishList, true, comment.getText(), itemId);
```suggestion
               NotificationsService.notify(NotificationType.ADD_NOTE, user, wishList, true, comment.getText(), itemId);
```

2020-10-28 09:21 UTC, patou approved these changes

2020-10-28 11:27 UTC, merged